"""This was added by Brian as general documentation of the protocol."""

# These are Notch's official names for the packets.
# This project tends to use lower-case versions of these names,
# and packets are defined in packets.py.
# A high-level string parsing lib (construct) is used to implement the
# wire protocol.

# This version of the wire protocol is current -- whereas the version used
# by the bot may or may not be current.  Further reference is available at
# http://mc.kev009.com/Protocol
proto_name_map = (('Keep Alive', 0),
                  ('Login Request', 1),
                  ('Handshake', 2),
                  ('Chat Message', 3),
                  ('Time Update', 4),
                  ('Entity Equipment', 5),
                  ('Spawn Position', 6),
                  ('Use Entity', 7),
                  ('Update Health', 8),
                  ('Respawn', 9),
                  ('Player', 10),
                  ('Player Position', 11),
                  ('Player Look', 12),
                  ('Player Position and Look', 13),
                  ('Player Digging', 14),
                  ('Player Block Placement', 15),
                  ('Held Item Change', 16),
                  ('Use Bed', 17),
                  ('Animation', 18),
                  ('Entity Action', 19),
                  ('Spawn Named Entity', 20),
                  ('Collect Item', 22),
                  ('Spawn Object/Vehicle', 23),
                  ('Spawn Mob', 24),
                  ('Spawn Painting', 25),
                  ('Spawn Experience Orb', 26),
                  ('Entity Velocity', 28),
                  ('Destroy Entity', 29),
                  ('Entity', 30),
                  ('Entity Relative Move', 31),
                  ('Entity Look', 32),
                  ('Entity Look and Relative Move', 33),
                  ('Entity Teleport', 34),
                  ('Entity Head Look', 35),
                  ('Entity Status', 38),
                  ('Attach Entity', 39),
                  ('Entity Metadata', 40),
                  ('Entity Effect', 41),
                  ('Remove Entity Effect', 42),
                  ('Set Experience', 43),
                  ('Chunk Data', 51),
                  ('Multi Block Change', 52),
                  ('Block Change', 53),
                  ('Block Action', 54),
                  ('Block Break Animation', 55),
                  ('Map Chunk Bulk', 56),
                  ('Explosion', 60),
                  ('Sound Or Particle Effect', 61),
                  ('Named Sound Effect', 62),
                  ('Change Game State', 70),
                  ('Spawn Global Entity', 71),
                  ('Open Window', 100),
                  ('Close Window', 101),
                  ('Click Window', 102),
                  ('Set Slot', 103),
                  ('Set Window Items', 104),
                  ('Update Window Property', 105),
                  ('Confirm Transaction', 106),
                  ('Creative Inventory Action', 107),
                  ('Enchant Item', 108),
                  ('Update Sign', 130),
                  ('Item Data', 131),
                  ('Update Tile Entity', 132),
                  ('Increment Statistic', 200),
                  ('Player List Item', 201),
                  ('Player Abilities', 202),
                  ('Tab-complete', 203),
                  ('Client Settings', 204),
                  ('Client Statuses', 205),
                  ('Plugin Message', 250),
                  ('Encryption Key Response', 252),
                  ('Encryption Key Request', 253),
                  ('Server List Ping', 254),
                  ('Disconnect/Kick', 255))