#! python
# -*- coding: utf-8 -*-
"""..this will be faster than manually copying all of the minecraft item info
from the website, and it will allow us to update in the future as things
change.
"""

from bs4 import BeautifulSoup
from urllib import urlopen
from collections import namedtuple

ADDRESS = "http://www.wiki.vg/Entities"

# compared against table.tr.text.split()
mob_data_identifier = 'Type Name x, z y'.split()
object_data_identifier = 'Type Name x, z y'.split()


MobEntityData = namedtuple('MobEntityData', 'number name width height')
ObjectEntityData = namedtuple('ObjectEntityData', 'number name width height')


def parse_mob_data(table):
    """parse_mob_data(entity_data_table) -> list of EntityData objects
    Takes a block data table, returns the entity data from that table as a list
    of EntityData objects.
    """
    result = []
    for t in table('tr'):
        if t.text.split() == mob_data_identifier:
            continue
        data = t('td')
        number = int(data[0].text.strip())
        name = data[1].text.strip()
        width_text = data[2].text.split(' *')[0].rstrip('?').strip()
        width = float(width_text) if width_text else None
        height_text = data[3].text.split(' *')[0].rstrip('?').strip()
        height = float(height_text) if height_text else None
        result.append(MobEntityData(number, name, width, height))
    return result


def get_mob_data(tables):
    """Takes a list of tables, returns a list of EntityData objects."""
    item_tables = [table for table in tables
                   if table.tr.text.split() == mob_data_identifier]
    result = []
    for table in item_tables:
        result.extend(parse_mob_data(table))
    return result


def parse_object_data(table):
    """parse_object_data(object_data_table) -> list of ItemData objects
    Takes an item data table, returns the item data from that table as a list
    of ItemData objects."""
    result = []
    for t in table('tr'):
        if t.text.split() == object_data_identifier:
            continue
        data = t('td')
        number = int(data[0].text.strip())
        name = data[1].text.strip()
        width_text = data[2].text.split(' *')[0].rstrip('?').strip()
        width = float(width_text) if width_text else None
        height_text = data[3].text.split(' *')[0].rstrip('?').strip()
        height = float(height_text) if height_text else None
        result.append(ObjectEntityData(number, name, width, height))
    return result


def get_object_data(tables):
    """Takes a list of tables, returns a list of item data."""
    item_tables = [table for table in tables
                   if table.tr.text.split() == object_data_identifier]
    result = []
    for table in item_tables:
        result.extend(parse_object_data(table))
    return result


def update_data(filename, noisy=True, fmt='json'):
    """Grab the data from the minecraft site, and store it in the given file,
    using the given format.
    fmt := The format to use.  Should be one of: pickle, json, repr or python
    repr will write an 'eval'able item, and python will write an importable
    module.
    """
    mobs, objects = fetch_data(noisy=noisy)
    data = {'mobs': [dict(i.__dict__) for i in mobs],
            'objects': [dict(i.__dict__) for i in objects]}
    if fmt == 'pickle':
        with open(filename, 'wb') as f:
            try:
                import cPickle as pickle
            except ImportError:
                import pickle
            p = pickle.Pickler(f)
            data = {'mobs': mobs, 'objects': objects}
            p.dump(data)
    elif fmt == 'json':
        import json
        with open(filename, 'w') as f:
            f.write(json.dumps(data, indent=4))
    elif fmt == 'repr':
        from pprint import pformat
        with open(filename, 'w') as f:
            f.write(pformat(data, indent=4))
    elif fmt == 'python':
        from pprint import pformat
        f = open(filename, 'w')
        f.write("\n")
        f.write("# autogenerated file\n\n")
        f.write("from collections import namedtuple\n")
        m = ("MobEntityData = namedtuple('MobEntityData',"
             " 'number name width height')")
        o = ("ObjectEntityData = namedtuple('ObjectEntityData', "
             "'number name width height')")
        f.write("%s\n%s\n\n" % (m, o))
        f.write("mobs = %s\n" % pformat(mobs, indent=4))
        f.write("objects = %s\n" % pformat(objects, indent=4))
        f.close()
    else:
        raise ValueError("Unrecognized format: " + fmt)
    if noisy:
        print "Fetch complete."


def download_soup(url, noisy=True):
    if noisy:
        print "Fetching name data.."
    page_data = urlopen(url).read()
    if noisy:
        print "Parsing data.."
    soup = BeautifulSoup(page_data)
    return soup


def fetch_data(noisy=True):
    tables = download_soup(ADDRESS)('table')
    mob_data = get_mob_data(tables)
    object_data = get_object_data(tables)
    return mob_data, object_data


def main():
    import sys
    USAGE = """Fetch the item list from the minecraft wiki.
    Usage:
        {} [filename]
    If filename is given, write to that, using the extension to guess type:
        .py: importable python module
        .json: json
        .pkl, .pickle: python pickle
        .eval: python data parsable with 'eval'
        Anything else: use json
    If not, print the information to the screen.
    """
    if len(sys.argv) > 2:
        print USAGE
        exit(1)
    elif len(sys.argv) == 2:
        for arg in sys.argv[1:]:
            if arg.lower() in ['--help', 'help', '/?', '-?', '/help']:
                print USAGE
                exit(0)
        fname = sys.argv[1]
        if fname.lower().endswith('.py'):
            fmt = 'python'
        elif fname.lower().endswith('.json'):
            fmt = 'json'
        elif fname.lower().endswith(('.pkl', '.pickle')):
            fmt = 'pickle'
        elif fname.lower().endswith('.eval'):
            fmt = 'repr'
        else:
            fmt = 'json'
        update_data(sys.argv[1], noisy=True, fmt=fmt)
        exit(0)
    object_data, entity_data = fetch_data(noisy=True)
    for line in object_data:
        print line
    for line in entity_data:
        print line


if __name__ == "__main__":
    main()

